### ISSUE TITLE
Successful installation not working 

### ISSUE THREAD

**Issue by RudiBoy95** [TheWildJames/OnePlus_KernelSU_SUSFS#1]
Neither on .305 or .406 

![Screenshot_2024-12-20-19-04-11-69_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/user-attachments/assets/5ab3d038-a749-4dac-86f1-dfbe1adc2e81)
![Screenshot_2024-12-20-19-06-00-28_baaa51257c82a8b3f281ce09e6f2493f](https://github.com/user-attachments/assets/f6e56fe8-ff9a-4233-8b60-c2b9c46642a2)

**Comment by TheWildJames** [comment]
use r10 of module
